### ISSUE TITLE
FEAT REQUEST: Verbose option ?

### ISSUE THREAD

**Issue by skyf0l** [mattrobenolt/ps-http-sim#10]
When using the planetscale adapter with prisma, some requests fail randomly. It would be nice to have some logs to help me understand where the problem is (like a --verbose or --debug)

I got this:
```
DatabaseError: Forbidden
    at postJSON (file:///workspaces/monorepo/node_modules/.pnpm/@planetscale+database@1.16.0/node_modules/@planetscale/database/dist/index.js:148:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.execute (file:///workspaces/monorepo/node_modules/.pnpm/@planetscale+database@1.16.0/node_modules/@planetscale/database/dist/index.js:84:19)
    at async PlanetScaleController.get (file:///workspaces/monorepo/node_modules/.pnpm/@lucia-auth+adapter-mysql@3.0.0_@planetscale+database@1.16.0_lucia@3.0.1/node_modules/@lucia-auth/adapter-mysql/dist/drivers/planetscale.js:13:26)
    at async PlanetScaleAdapter.getUserFromSessionId (file:///workspaces/monorepo/node_modules/.pnpm/@lucia-auth+adapter-mysql@3.0.0_@planetscale+database@1.16.0_lucia@3.0.1/node_modules/@lucia-auth/adapter-mysql/dist/base.js:59:24)
    at async Promise.all (index 1)
    at async PlanetScaleAdapter.getSessionAndUser (file:///workspaces/monorepo/node_modules/.pnpm/@lucia-auth+adapter-mysql@3.0.0_@planetscale+database@1.16.0_lucia@3.0.1/node_modules/@lucia-auth/adapter-mysql/dist/base.js:21:49)
    at async Lucia.validateSession (file:///workspaces/monorepo/node_modules/.pnpm/lucia@3.0.1/node_modules/lucia/dist/core.js:61:49)
    at async sessionMiddleware (/workspaces/monorepo/apps/studio/src/hooks.server.ts:18:29)
    at async file:///workspaces/monorepo/node_modules/.pnpm/sveltekit-helmet@1.0.2/node_modules/sveltekit-helmet/lib/index.js:13:26 {
  status: 403,
  body: { code: 'internal', message: 'Forbidden' }
}
```

It never happen using planetscale or a simple mysql in local

**Comment by skyf0l** [comment]
My problem seems to be linked to #7

**Comment by skyf0l** [comment]
Fixed by https://github.com/mattrobenolt/ps-http-sim/issues/7#issuecomment-1894607212
