### ISSUE TITLE
Expose mysql API ??

### ISSUE THREAD

**Issue by skyf0l** [mattrobenolt/ps-http-sim#11]
Using [Drizzle-kit](https://orm.drizzle.team/kit-docs), in my `drizzle.config.ts` I can directly reference my PlanetScale URL and push the schema

```ts
// drizzle.config.ts
import type { Config } from "drizzle-kit";

export default {
  schema: "./src/schema.ts",
  out: "./drizzle",
  driver: "mysql2",
  dbCredentials: {
    uri: 'mysql://xxx:xxx@aws.connect.psdb.cloud/xxx?ssl={"rejectUnauthorized":true}',
  },
} satisfies Config;
```

```console
$ npm drizzle-kit push:mysql

drizzle-kit: v0.20.14
drizzle-orm: v0.29.4

No config path provided, using default path
Reading config file '/workspaces/monorepo/libs/database/drizzle.config.ts'
Reading schema files:
/workspaces/monorepo/libs/database/src/schema.ts

[✓] Changes applied
```

But it doesn't work using `ps-http-sim` (url `mysql://root:root@db-proxy:3900/planetscale`)
```console
$ npm drizzle-kit push:mysql

drizzle-kit: v0.20.14
drizzle-orm: v0.29.4

No config path provided, using default path
Reading config file '/workspaces/monorepo/libs/database/drizzle.config.ts'
/workspaces/monorepo/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:44339
      const createConnectionErr = new Error();
                                  ^

Error: connect ETIMEDOUT
    at createConnection2 (/workspaces/monorepo/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:44339:35)
    at connectToMySQL (/workspaces/monorepo/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:61922:64)
    at Command.<anonymous> (/workspaces/monorepo/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:63084:28) {
  code: 'ETIMEDOUT',
  errno: undefined,
  sqlState: undefined
}
```

This works using the direct mysql endpoint. I have no precise idea what's going on, but I imagine that planetscale must expose a mysql endpoint, but not ps-http-sim.

**Comment by skyf0l** [comment]
That's good, you may have to add it to the readme

**Comment by mattrobenolt** [comment]
PRs accepted.
